# s'exécute a chaque push
on: push
name: CI Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Se déplacer à la racine du repository (v4)
        uses: actions/checkout@v4
      - name: Installer les dépendances npm
        uses: npm install
      - name: Lancer les tests
        uses: npm test
      - name: Vérifier la syntaxe avec ESLint
        uses: npm run lint
      - name: Génére un artifact de build
        uses: mkdir dist && echo "Build successful" > dist/build.txt
      - name: Envoie un message dans la console à la fin
        uses: echo "CI Workflow completed successfully"
