# Le fichier YAML est à compléter
on: push
name: CI Workflow
jobs :
  build :
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: mkdir dist && echo "Build successful" > dist/build.txt
      - run: echo "CI Workflow completed successfully"