# s'exécute a chaque push
on: [push,workflow_dispatch]
  branches-ignore:
  - 'feature/*'
name: CI Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Se déplacer à la racine du repository (v4)
        uses: actions/checkout@v4
      - name: Installer les dépendances npm
        run: npm install
      - name: Lancer les tests
        run: npm test
      - name: Génére un artifact de build
        run: mkdir dist && echo "Build successful" > dist/build.txt
      - name: Envoie un message dans la console à la fin
        run: echo "CI Workflow completed successfully"
  lint :
    runs-on: ubuntu-latest
    steps:
      - name: Se déplacer à la racine du repository (v4)
        uses: actions/checkout@v4
      - name: Vérifier la syntaxe avec ESLint
        run: npm run lint
